import Head from 'next/head'
import Typography from '@material-ui/core/Typography';
import Link from '@material-ui/core/Link';
import { makeStyles } from '@material-ui/core'


const useStyles = makeStyles({
  
})

export default function Loading() {
  const classes = useStyles()
  return (
    <>
      <Head>
        <title>Loading Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography component="h3" variant="h3">
        Loading Example
      </Typography>

    </>
  )
}
